# Generated by Django 6.0.1 on 2026-01-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_jobbenefit_jobrequirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
    ]
