# Generated by Django 6.0.1 on 2026-01-16 14:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
