# Generated by Django 6.0.1 on 2026-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerapplication',
            name='email',
        ),
        migrations.AddField(
            model_name='jobseekerapplication',
            name='cv',
            field=models.FileField(default='hello.pdf', upload_to='cvs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobseekerapplication',
            name='phone',
            field=models.CharField(default='9000', max_length=10),
            preserve_default=False,
        ),
    ]
