# Generated by Django 6.0.1 on 2026-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_jobseekerapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome icon classname only, e.g. book, pen', max_length=100),
        ),
    ]
